// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uywdrexynziahknjnqwd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV5d2RyZXh5bnppYWhrbmpucXdkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM0ODA1MjQsImV4cCI6MjA3OTA1NjUyNH0.-uab_Aw_7cvfepnOt1l50CV8_aHw1QwhwAUhYr7zpoM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});