// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rmavcuaexylvnauuykps.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJtYXZjdWFleHlsdm5hdXV5a3BzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQwNzQ1OTQsImV4cCI6MjA3OTY1MDU5NH0.00oSb0QCCxVGnVRtuTuF-iL0zs7j1CykDNo2GZoSEMM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});